// Generated by scripts/setup-5.mjs from _flows/Status.ts — regenerate instead of editing flow steps.
import { test, expect, type Page } from '@playwright/test';
import { statusTestCases } from './Status.data';
import { applyStatusInputs } from './Status.helper';

async function enterStatusPage(page: Page): Promise<void> {
  await page.goto('http://localhost:8787/admin/login?callbackUrl=%2Fadmin');
}

async function defaultVerify(page: Page): Promise<void> {
  const errorDialog = page
    .locator('[role="dialog"], .modal, .swal2-popup')
    .filter({ hasText: /error|ผิดพลาด|ข้อผิดพลาด/i });
  await expect(errorDialog).toHaveCount(0, { timeout: 10_000 });
  await expect(page).toHaveURL(/^http:\/\/localhost:8787/, { timeout: 10_000 });
}

test.describe('Status', () => {
  test.beforeEach(async ({ page }) => {
    await enterStatusPage(page);
  });

  for (const testData of statusTestCases) {
    test(`${testData.testCaseId} - ${testData.scenario}`, async ({ page }) => {
      // === DATA ===
      await applyStatusInputs(page, testData);
      await page.getByRole('button', { name: 'บันทึก' }).click();

      await defaultVerify(page);
    });
  }
});
