// Generated by scripts/setup-5.mjs from _scenarios/Status.csv
import type { StatusTestCase } from './Status.types';

export const statusTestCases: StatusTestCase[] = [
  {
    testCaseId: 'TC001',
    scenario: 'Change Status',
    values: [
      '1 Oct 12:00 test นวดไทย ฿350', 'ยกเลิก',
    ],
  },
];
