// Generated by scripts/form-login.mjs from a codegen recording — run by Authen/Form-Login/setup-form-auth.bat
// Credentials come from environment variables set by that script; never write them here.
import { test as setup, expect } from '@playwright/test';
import { getFormLoginCredentials, saveStorageState } from '../../../../Authen/Form-Login/form-auth.helper';

setup('Create form login session', async ({ page }) => {
  const { username, password, sessionStoragePath } = getFormLoginCredentials();

  await page.goto('http://localhost:8787/admin/login?callbackUrl=%2Fadmin');
  await page.getByRole('textbox', { name: 'อีเมล' }).fill(username);
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill(password);
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();

  // Logged in: no longer on a login page (on failure the error shows the URL it stayed on)
  await expect(page).not.toHaveURL(/login|signin|sign-in/i);

  await saveStorageState({ page, outputPath: sessionStoragePath });
});
