// Generated by scripts/setup-5.mjs from _flows/Bookings.ts — regenerate instead of editing flow steps.
import { test, expect, type Page } from '@playwright/test';
import { bookingsTestCases } from './Bookings.data';
import { applyBookingsInputs } from './Bookings.helper';

async function enterBookingsPage(page: Page): Promise<void> {
  await page.goto('http://localhost:8787/');
}

async function defaultVerify(page: Page): Promise<void> {
  const errorDialog = page
    .locator('[role="dialog"], .modal, .swal2-popup')
    .filter({ hasText: /error|ผิดพลาด|ข้อผิดพลาด/i });
  await expect(errorDialog).toHaveCount(0, { timeout: 10_000 });
  await expect(page).toHaveURL(/^http:\/\/localhost:8787/, { timeout: 10_000 });
}

test.describe('Bookings', () => {
  test.beforeEach(async ({ page }) => {
    await enterBookingsPage(page);
  });

  for (const testData of bookingsTestCases) {
    test(`${testData.testCaseId} - ${testData.scenario}`, async ({ page }) => {
      await page.locator('#top').getByRole('link', { name: 'จองเลย →' }).click();
      // === DATA ===
      await applyBookingsInputs(page, testData);
      await page.getByRole('button', { name: 'ยืนยันการจอง →' }).click();
      await page.getByRole('link', { name: 'กลับหน้าแรก' }).click();

      await defaultVerify(page);
    });
  }
});
