// Generated by scripts/setup-5.mjs from _scenarios/Bookings.csv
import type { BookingsTestCase } from './Bookings.types';

export const bookingsTestCases: BookingsTestCase[] = [
  {
    testCaseId: 'TC001',
    scenario: 'Bookings',
    values: [
      'นวดไทย ฿ 350 60 นาที', 'วันพฤหัสบดีที่ 1 ตุลาคม', '12:00', 'test', '0987654321',
    ],
  },
];
