// Generated by scripts/setup-5.mjs — extend via Setup 6.
import type { Locator, Page } from '@playwright/test';
import type { BookingsTestCase } from './Bookings.types';
import { bookingsLocators } from '../_locators/Bookings';

// Accepts both static-only and parametric locator arrays.
const locators: ReadonlyArray<(page: Page, value?: string) => Locator> = bookingsLocators;

async function applyItem(page: Page, index: number, item: string): Promise<void> {
  const locatorFn = locators[index];
  if (!locatorFn) {
    throw new Error(`No locator at index ${index}`);
  }

  // Action marker (currently supported: |click)
  if (item.startsWith('|')) {
    const action = item.slice(1);
    switch (action) {
      case 'click': {
        if (locatorFn.length === 2) {
          throw new Error(
            `Locator at index ${index} is parametric — CSV must give a button name, not |click`
          );
        }
        await locatorFn(page).click();
        return;
      }
      default:
        throw new Error(`Unknown action: |${action}`);
    }
  }

  // Parametric locator: value = name of the element to click
  if (locatorFn.length === 2) {
    await locatorFn(page, item).click();
    return;
  }

  // Static locator + text: dispatch by locator type
  const target = locatorFn(page);
  const locatorCode = locatorFn.toString();

  if (/getByRole\(\s*['"]textbox['"]/.test(locatorCode)) {
    await target.fill(item);
  } else if (/getByRole\(\s*['"]combobox['"]/.test(locatorCode) || locatorCode.includes('ng-select')) {
    await target.click();
    await page.getByRole('option', { name: item }).click();
  } else {
    throw new Error(
      `Cannot dispatch text value at index ${index} — unknown locator type. Locator: ${locatorCode}`
    );
  }
}

export async function applyBookingsInputs(page: Page, testData: BookingsTestCase): Promise<void> {
  if (testData.values.length !== locators.length) {
    throw new Error(
      `${testData.testCaseId}: ${testData.values.length} values, expected ${locators.length}`
    );
  }
  for (let i = 0; i < testData.values.length; i++) {
    const item = testData.values[i];
    if (item === '') continue;
    await applyItem(page, i, item);
  }
}
